name: easy_violin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^13.1.0
  image: ^4.10.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  youtube_explode_dart: ^3.1.0
  http: ^1.2.0
  onnxruntime: ^1.4.1
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
